import { createContext } from "react";

const FirebaseContext = createContext();

export default FirebaseContext;
//HCAEMOS ESTO ARA PODER IMPORTARLO EN NUESTRA APP.JS DESDE AHI TODAS LAS FUNCIONES SE PODRAN PROPAGAR A LO LARGOR DE TODOS LOS COMPONENTES SIN ESTAR PASANDOLOS POR PROX
